# Плагин был сделан DeC0de (Egon)
# Для SpigotMc.ru 🧡

# Права доступа:
# /pbc - pbc.use
# /pbca - pbc.admin
# /bpbc - pbc.ban
# /pbc reload - pbc.reload
# /ubpbc - pbc.unban

# Свои placeholder-ы - %playermsg%, %broadplayer%, %banned% и %admin%

Menu:

# Название инвентаря
  name: "PBC-GUI Админа"
  secondGuiName: "Одобрить/Отклонить"

# Сообщегия броадкаста
  broadcast: "&6(Объявления)&f %playermsg% &7(от: %broadplayer%)"

  waitmessage:
    - "&aВы успешно отправили ваш текст на проверку"
    - "&2Ждите"

# Сообщения если не прав
  noperms: "&cУ вас нет прав!"

# Сообщегия когда игрок может сново исп броадкаст
  whounbanned:
    - "&aВы может сново использовать &2/pbc"

# Сообщегия тому кто разбанил
  unbanmessage:
    - "&2Успешная разблокировка &a%banned%"

# Сообщегия тому кого забанили
  whobannedmessage:
    - "&cВам был заблокирован доступ &4/pbc"

# Сообщегия тому кто забанил
  bannedplayermessage:
    - "&2Успешно"
    - "&aЗаблокирован %banned%"

# Сообщегия
  unknowcmdpbc:
    - "&6/pbc &7- &fкоманда для отправки предложения сообщения"
  unknowcmdbanpbc:
    - "&6/bpbc &eНик &7- &fдля блокировки доступа к команде"
  unknownunbanpbc:
    - "&6/ubpbc &eНик &7- &fдля разблокировки доступа к команде"

  notfound:
    - "&cИгрок %banned% не найден"

  reloadconfig: "&aПлагин перезагружен"

# Если ркон консоль будет пытаться
  notplayer: "Только Игрок Может Делать БроадКасты"


# Если игрок наводит курсор на текст
  hover: true

  hovermsg: "&aАдминистратор &2%admin% &aодобрил этот БроадКаст"
